name: build and test
on:
  push:

  workflow_dispatch: # this is a nice option that will enable a button w/ inputs
    inputs:
      git-ref:
        description: Git Ref (Optional)    
        required: false
jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install ninja 
        run: sudo apt install ninja-build -y

      - name: Install meson
        run: pip3 install meson

      - name: build
        run: |
          mkdir build; cd build
          meson ..
          ninja
          python3 -m pytest test/
